steps:
  # Run tests
  - name: golang:1.18
    entrypoint: /bin/bash
    args:
      - -c
      - |
        go test -v ./...
        echo "successfully tested"

  # TODO: Need to refactor this code with simple secrets.yaml creation
  - name: golang:1.18
    entrypoint: /bin/bash
    args:
      - -c
      - |
        echo "ms_api:" >> secrets.yaml
        echo "  key: ${_MS_API_KEY_SECRET}" >> secrets.yaml
        echo "notifications:" >> secrets.yaml
        echo "  should_send_email: true" >> secrets.yaml
        echo "uploads:" >> secrets.yaml
        echo "  should_upload_insights_output_to_gcp: true" >> secrets.yaml

  # Running orchestrator
  - name: golang:1.18
    entrypoint: /bin/bash
    args:
      - -c
      - |
        go run .
        echo "done"

  # Upload to GCP
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: 'bash'
    args:
      - -c
      - |
        gsutil -m cp -r tmp/build/websites/* gs://letf_website/

options:
  logging: CLOUD_LOGGING_ONLY
  diskSizeGb: '250'