steps:
  # Run tests
  - name: golang:1.17
    entrypoint: /bin/bash
    args:
      - -c
      - |
        go test -v ./...
        echo "successfully tested"

  # TODO: Need to refactor this code with simple secrets.yaml creation
  - name: golang:1.17
    entrypoint: /bin/bash
    args:
      - -c
      - |
        echo "ms_api:" >> secrets.yaml
        echo "  key: ${_MS_API_KEY_SECRET}" >> secrets.yaml
        echo "notifications:" >> secrets.yaml
        echo "  should_send_email: true" >> secrets.yaml
        echo "uploads:" >> secrets.yaml
        echo "  should_upload_insights_output_to_gcp: true" >> secrets.yaml

  # Running orchestrator
  - name: golang:1.17
    entrypoint: /bin/bash
    id: running_orchestrator
    args:
      - -c
      - |
        go run .
        echo "done"
    timeout: 60000s

  # Upload to GCP
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: 'bash'
    args:
      - -c
      - |
        du -sh .
        gsutil -m cp -r tmp/build/websites/* gs://letf_website/
    timeout: 60000s
    waitFor:
      - running_orchestrator

timeout: 80000s

options:
  logging: CLOUD_LOGGING_ONLY
  diskSizeGb: '250'
  machineType: E2_HIGHCPU_8