name: Deploy To DO

on:
  schedule:
    - cron: '0 22 * * 1-5'
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy_to_do:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    # TODO: Need to refactor this code with simple secrets.yaml creation
    - name: Setup secrets.yaml
      run: |
        echo "ms_api:" >> secrets.yaml
        echo "  key: ${{secrets.MS_API_KEY_SECRET}}" >> secrets.yaml
        echo "alpha_vantage:" >> secrets.yaml
        echo "  key: ${{secrets.ALPHA_VANTAGE_KEY_SECRET}}" >> secrets.yaml
        
        cp secrets.yaml secrets_production.yaml
        
        echo "notifications:" >> secrets.yaml
        echo "  should_send_email: true" >> secrets.yaml
        echo "uploads:" >> secrets.yaml
        echo "  should_upload_insights_output_to_gcp: true" >> secrets.yaml
        echo "test_config:" >> secrets.yaml
        echo "  max_server_run_time: 10" >> secrets.yaml

    - name: Run orchestrator
      run: |
        go run .

    - name: Resetting Secrets for production
      run: |
        rm secrets.yaml
        cp secrets_production.yaml secrets.yaml

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Generate GITHUB_SHA
      id: github-sha
      shell: bash
      # SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7) -- Removed this
      run: |
        SHORT_SHA=prod
        echo "::set-output name=sha::$SHORT_SHA"

    - name: Build container image
      run: docker build . -t registry.digitalocean.com/stocks/stocks:${{steps.github-sha.outputs.sha}}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600

    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/stocks/stocks:${{steps.github-sha.outputs.sha}}