# This is a basic workflow to help you get started with Actions

name: Check for TODOs in Code

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  todo:
    concurrency:
      group: ${{ github.ref }}-${{ github.job }}-${{ github.workflow }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4.6.3

