name: Run Prod

on:
  schedule:
    - cron: '0 22 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    # TODO: Need to refactor this code with simple secrets.yaml creation
    - name: Setup secrets.yaml
      run: |
        echo "ms_api:" >> secrets.yaml
        echo "  key: ${{secrets.MS_API_KEY_SECRET}}" >> secrets.yaml
        echo "notifications:" >> secrets.yaml
        echo "  should_send_email: true" >> secrets.yaml
        echo "uploads:" >> secrets.yaml
        echo "  should_upload_insights_output_to_gcp: true" >> secrets.yaml
        echo "test_config:" >> secrets.yaml
        echo "  max_server_run_time: 10" >> secrets.yaml

    - name: Run orchestrator
      run: |
        go run .
        

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Generate GITHUB_SHA
      id: github-sha
      shell: bash
      run: |
        SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        echo "::set-output name=sha::$SHORT_SHA"
    - name: Publish Image to Digital Ocean Container Registry
      shell: bash
      run: |
        doctl registry login --expiry-seconds 600
        docker build . -t registry.digitalocean.com/stocks:${{steps.github-sha.outputs.sha}}
        docker push registry.digitalocean.com/stocks:${{steps.github-sha.outputs.sha}}

    - name: DigitalOcean App Platform deployment
      uses: digitalocean/app_action@main
      with:
        app_name: stocks-docker-image-droplet
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        images: '[{
                    "name": "web",
                    "repository": "registry.digitalocean.com/stocks",
                    "tag": "${{steps.github-sha.outputs.sha}}"
                  }
                ]'