name: Run and send email alert

on:
  schedule:
    - cron: '0 22 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    # TODO: Need to refactor this code with simple config.yaml creation
    - name: Setup config.yaml
      run: |
        echo "ms_api:" >> config.yaml
        echo "  host: ms-finance.p.rapidapi.com" >> config.yaml
        echo "  url: https://ms-finance.p.rapidapi.com/market/v2/get-movers" >> config.yaml
        echo "  key: ${{secrets.MS_API_KEY_SECRET}}" >> config.yaml
        echo "notifications:" >> config.yaml
        echo "  should_send_email: true" >> config.yaml
        echo "directories:" >> config.yaml
        echo "  tmp: tmp" >> config.yaml
        echo "  build: tmp/build" >> config.yaml
        echo "  artifacts: tmp/build/artifacts" >> config.yaml
        echo "  websites: tmp/build/artifacts/websites" >> config.yaml

    - name: Run orchestrator
      run: |
        cat config.yaml
        go run .

    # TODO: Hardcoded for now, need to fix this in future
    # Need to support sending email to multiple people
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Optional (recommended): mail server username:
        username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.GMAIL_ALERTER_APP_KEY}}
        # Required mail subject:
        subject: Github Actions job result
        # Required recipients' addresses:
        to: 05.dreaded_baobabs@icloud.com
        # Required sender full name (address can be skipped):
        from: Alerter GitHub # <user@example.com>
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional HTML body read from file:
        html_body: file://${{ github.workspace }}/tmp/Ravi_Vooda_Notifications__tmp/email.html
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: false
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: low

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/659322829339/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
        service_account: 'github-actions-upload@stocks-348021.iam.gserviceaccount.com'

    # TODO: Hardcoded path, need to use $BUILD_ARTIFACTS_PATH from above
    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: tmp/build/artifacts
        destination: 'letf_overlaps/github_action'
        parent: false

#    # Example of using the output
#    - id: 'upload_'
#      uses: 'foo/bar@main'
#      env:
#        files: '${{ steps.upload-folder.outputs.uploaded }}'